name: Alice's Appetizers
location: MediaCityUK
menu:
- name: &id001 Garlic bread
  price: 5.0
- <<: *id001
  price 3.0
- name: Olives
  price: 4.0
- name: Pizza
  price: !!float 10
- name: Mac & Cheese
  price: 10.0
