name: Alice's Appetizers
location: MediaCityUK
open: !!str 1200
close: !!str 2300
menu: &menu
- name: Garlic bread
  price: 5.0
- name: Olives
  price: 4.0
- name: Pizza
  price: !!float 10
- name: Mac & Cheese
  price: 10.0
